spring:
  cloud:
    azure:
      cosmos:
        database: ${COSMOSNAME}
        endpoint: ${COSMOSDBURI}
        key: ${COSMOSDBKEY}

#  app.component.topic.carro=topico-<NOMEDOMICROSERVICO>-<NOMEDAENTIDADE>
#  app.component.service=servicebus-pubsub
app:
  component:
    topic:
      subject: topico-cursodeextensao-subject
      enrollment: topico-cursodeextensao-enrollment
      course: topico-cursodeextensao-course


    service: servicebus-pubsub