spring:
  cloud:
    azure:
      cosmos:
        database: dbcursodeextensao
        endpoint: https://localhost:8081/
        key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMs